CREATE DATABASE employee;
USE employee;

CREATE TABLE empdata (
    Id VARCHAR(20) PRIMARY KEY,
    Name VARCHAR(100),
    Email_Id VARCHAR(100),
    Phone_no VARCHAR(15),
    Address VARCHAR(255),
    Post VARCHAR(100),
    Salary INT
);
select * from empdata;
TRUNCATE TABLE empdata;
INSERT INTO empdata
(Id, Name, Email_Id, Phone_no, Address, Post, Salary)
SELECT
CONCAT('EMP', n),
CONCAT('Employee_', n),
CONCAT('employee', n, '@gmail.com'),
CONCAT('98', LPAD(n, 8, '0')),
CONCAT('Address ', n),
'Developer',
30000 + MOD(n,50000)
FROM (
SELECT a.N + b.N*10 + c.N*100 + d.N*1000 + 1 AS n
FROM
(SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a
CROSS JOIN
(SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b
CROSS JOIN
(SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c
CROSS JOIN
(SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2) d
) numbers
WHERE n <= 2000;
SELECT COUNT(*) FROM empdata;

SELECT MAX(Salary) FROM empdata;

SELECT AVG(Salary) FROM empdata;

SELECT * FROM empdata ORDER BY Salary DESC LIMIT 10;

SELECT Post, COUNT(*) FROM empdata GROUP BY Post;